# Generated by Django 4.1.4 on 2022-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario_alter_evento_data_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='Hospital', max_length=100),
            preserve_default=False,
        ),
    ]
